// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cinemas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCinema = `-- name: CreateCinema :one
INSERT INTO cinemas (name, address, location_coordinates)
VALUES ($1, $2, $3)
RETURNING cinema_id, name, address, location_coordinates
`

type CreateCinemaParams struct {
	Name                string      `json:"name"`
	Address             string      `json:"address"`
	LocationCoordinates pgtype.Text `json:"location_coordinates"`
}

func (q *Queries) CreateCinema(ctx context.Context, arg CreateCinemaParams) (Cinema, error) {
	row := q.db.QueryRow(ctx, createCinema, arg.Name, arg.Address, arg.LocationCoordinates)
	var i Cinema
	err := row.Scan(
		&i.CinemaID,
		&i.Name,
		&i.Address,
		&i.LocationCoordinates,
	)
	return i, err
}

const deleteCinema = `-- name: DeleteCinema :exec
DELETE FROM cinemas WHERE cinema_id = $1
`

func (q *Queries) DeleteCinema(ctx context.Context, cinemaID int32) error {
	_, err := q.db.Exec(ctx, deleteCinema, cinemaID)
	return err
}

const getCinema = `-- name: GetCinema :one
SELECT cinema_id, name, address, location_coordinates FROM cinemas WHERE cinema_id = $1
`

func (q *Queries) GetCinema(ctx context.Context, cinemaID int32) (Cinema, error) {
	row := q.db.QueryRow(ctx, getCinema, cinemaID)
	var i Cinema
	err := row.Scan(
		&i.CinemaID,
		&i.Name,
		&i.Address,
		&i.LocationCoordinates,
	)
	return i, err
}

const listCinemas = `-- name: ListCinemas :many
SELECT cinema_id, name, address, location_coordinates FROM cinemas ORDER BY cinema_id LIMIT $1 OFFSET $2
`

type ListCinemasParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCinemas(ctx context.Context, arg ListCinemasParams) ([]Cinema, error) {
	rows, err := q.db.Query(ctx, listCinemas, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cinema{}
	for rows.Next() {
		var i Cinema
		if err := rows.Scan(
			&i.CinemaID,
			&i.Name,
			&i.Address,
			&i.LocationCoordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCinema = `-- name: UpdateCinema :one
UPDATE cinemas
SET name = $2, address = $3, location_coordinates = $4
WHERE cinema_id = $1
RETURNING cinema_id, name, address, location_coordinates
`

type UpdateCinemaParams struct {
	CinemaID            int32       `json:"cinema_id"`
	Name                string      `json:"name"`
	Address             string      `json:"address"`
	LocationCoordinates pgtype.Text `json:"location_coordinates"`
}

func (q *Queries) UpdateCinema(ctx context.Context, arg UpdateCinemaParams) (Cinema, error) {
	row := q.db.QueryRow(ctx, updateCinema,
		arg.CinemaID,
		arg.Name,
		arg.Address,
		arg.LocationCoordinates,
	)
	var i Cinema
	err := row.Scan(
		&i.CinemaID,
		&i.Name,
		&i.Address,
		&i.LocationCoordinates,
	)
	return i, err
}
