// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cinema struct {
	CinemaID            int32       `json:"cinema_id"`
	Name                string      `json:"name"`
	Address             string      `json:"address"`
	LocationCoordinates pgtype.Text `json:"location_coordinates"`
}

type Movie struct {
	MovieID     int32       `json:"movie_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Genre       []string    `json:"genre"`
	TrailerUrl  pgtype.Text `json:"trailer_url"`
}

type Permission struct {
	PermissionID int32  `json:"permission_id"`
	Role         string `json:"role"`
}

type Review struct {
	ReviewID  int32              `json:"review_id"`
	UserID    int32              `json:"user_id"`
	MovieID   int32              `json:"movie_id"`
	Rating    pgtype.Int4        `json:"rating"`
	Content   pgtype.Text        `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Showtime struct {
	ShowtimeID int32              `json:"showtime_id"`
	MovieID    int32              `json:"movie_id"`
	CinemaID   int32              `json:"cinema_id"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	Price      pgtype.Numeric     `json:"price"`
	Duration   int32              `json:"duration"`
}

type Ticket struct {
	TicketID      pgtype.UUID `json:"ticket_id"`
	ShowtimeID    int32       `json:"showtime_id"`
	UserID        int32       `json:"user_id"`
	SeatNumber    string      `json:"seat_number"`
	PaymentStatus pgtype.Text `json:"payment_status"`
}

type User struct {
	UserID          int32              `json:"user_id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Phone           pgtype.Text        `json:"phone"`
	FullName        string             `json:"full_name"`
	IsBlocked       pgtype.Bool        `json:"is_blocked"`
	PermissionLevel pgtype.Int4        `json:"permission_level"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
