// Code generated by sqlc. DO NOT EDIT.
// This file shows what `sqlc generate` produces.
// Run: sqlc generate

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// User represents a row from 'users'
type User struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Active       pgtype.Bool        `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Post represents a row from 'posts'
type Post struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	Title     string             `json:"title"`
	Content   pgtype.Text        `json:"content"`
	Published pgtype.Bool        `json:"published"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// GetPostWithAuthorRow is returned by GetPostWithAuthor
type GetPostWithAuthorRow struct {
	ID          int32              `json:"id"`
	Title       string             `json:"title"`
	Content     pgtype.Text        `json:"content"`
	Published   pgtype.Bool        `json:"published"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	AuthorID    int32              `json:"author_id"`
	AuthorName  string             `json:"author_name"`
	AuthorEmail string             `json:"author_email"`
}

// ListPostsWithAuthorsRow is returned by ListPostsWithAuthors
type ListPostsWithAuthorsRow struct {
	ID         int32              `json:"id"`
	Title      string             `json:"title"`
	Content    pgtype.Text        `json:"content"`
	Published  pgtype.Bool        `json:"published"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	AuthorID   int32              `json:"author_id"`
	AuthorName string             `json:"author_name"`
}

// CreateUserParams are the parameters for CreateUser
type CreateUserParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

// UpdateUserParams are the parameters for UpdateUser
type UpdateUserParams struct {
	ID    int32       `json:"id"`
	Name  pgtype.Text `json:"name"`
	Email pgtype.Text `json:"email"`
}

// CreatePostParams are the parameters for CreatePost
type CreatePostParams struct {
	UserID    int32       `json:"user_id"`
	Title     string      `json:"title"`
	Content   pgtype.Text `json:"content"`
	Published pgtype.Bool `json:"published"`
}

// ListUsersParams are the parameters for ListUsers
type ListUsersParams struct {
	Active pgtype.Bool `json:"active"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

// Helper functions for nullable types
func NullString(s string) pgtype.Text {
	return pgtype.Text{String: s, Valid: true}
}

func NullBool(b bool) pgtype.Bool {
	return pgtype.Bool{Bool: b, Valid: true}
}

func NullTime(t time.Time) pgtype.Timestamptz {
	return pgtype.Timestamptz{Time: t, Valid: true}
}
