// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package db

import (
	"context"
)

const getPermission = `-- name: GetPermission :one
SELECT permission_id, role FROM permissions WHERE permission_id = $1
`

func (q *Queries) GetPermission(ctx context.Context, permissionID int32) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermission, permissionID)
	var i Permission
	err := row.Scan(&i.PermissionID, &i.Role)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT permission_id, role FROM permissions ORDER BY permission_id
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.PermissionID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
