// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (user_id, movie_id, rating, content)
VALUES ($1, $2, $3, $4)
RETURNING review_id, user_id, movie_id, rating, content, created_at
`

type CreateReviewParams struct {
	UserID  int32       `json:"user_id"`
	MovieID int32       `json:"movie_id"`
	Rating  pgtype.Int4 `json:"rating"`
	Content pgtype.Text `json:"content"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.UserID,
		arg.MovieID,
		arg.Rating,
		arg.Content,
	)
	var i Review
	err := row.Scan(
		&i.ReviewID,
		&i.UserID,
		&i.MovieID,
		&i.Rating,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews WHERE review_id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, reviewID int32) error {
	_, err := q.db.Exec(ctx, deleteReview, reviewID)
	return err
}

const getReview = `-- name: GetReview :one
SELECT review_id, user_id, movie_id, rating, content, created_at FROM reviews WHERE review_id = $1
`

func (q *Queries) GetReview(ctx context.Context, reviewID int32) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, reviewID)
	var i Review
	err := row.Scan(
		&i.ReviewID,
		&i.UserID,
		&i.MovieID,
		&i.Rating,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listReviews = `-- name: ListReviews :many
SELECT
    r.review_id, r.user_id, r.movie_id, r.rating, r.content, r.created_at,
    u.full_name AS user_name,
    m.title AS movie_title
FROM reviews r
JOIN users u ON u.user_id = r.user_id
JOIN movies m ON m.movie_id = r.movie_id
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type ListReviewsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListReviewsRow struct {
	ReviewID   int32              `json:"review_id"`
	UserID     int32              `json:"user_id"`
	MovieID    int32              `json:"movie_id"`
	Rating     pgtype.Int4        `json:"rating"`
	Content    pgtype.Text        `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UserName   string             `json:"user_name"`
	MovieTitle string             `json:"movie_title"`
}

func (q *Queries) ListReviews(ctx context.Context, arg ListReviewsParams) ([]ListReviewsRow, error) {
	rows, err := q.db.Query(ctx, listReviews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsRow{}
	for rows.Next() {
		var i ListReviewsRow
		if err := rows.Scan(
			&i.ReviewID,
			&i.UserID,
			&i.MovieID,
			&i.Rating,
			&i.Content,
			&i.CreatedAt,
			&i.UserName,
			&i.MovieTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByMovie = `-- name: ListReviewsByMovie :many
SELECT
    r.review_id, r.user_id, r.movie_id, r.rating, r.content, r.created_at,
    u.full_name AS user_name,
    m.title AS movie_title
FROM reviews r
JOIN users u ON u.user_id = r.user_id
JOIN movies m ON m.movie_id = r.movie_id
WHERE r.movie_id = $1
ORDER BY r.created_at DESC
`

type ListReviewsByMovieRow struct {
	ReviewID   int32              `json:"review_id"`
	UserID     int32              `json:"user_id"`
	MovieID    int32              `json:"movie_id"`
	Rating     pgtype.Int4        `json:"rating"`
	Content    pgtype.Text        `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UserName   string             `json:"user_name"`
	MovieTitle string             `json:"movie_title"`
}

func (q *Queries) ListReviewsByMovie(ctx context.Context, movieID int32) ([]ListReviewsByMovieRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByMovie, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsByMovieRow{}
	for rows.Next() {
		var i ListReviewsByMovieRow
		if err := rows.Scan(
			&i.ReviewID,
			&i.UserID,
			&i.MovieID,
			&i.Rating,
			&i.Content,
			&i.CreatedAt,
			&i.UserName,
			&i.MovieTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews
SET rating = $2, content = $3
WHERE review_id = $1
RETURNING review_id, user_id, movie_id, rating, content, created_at
`

type UpdateReviewParams struct {
	ReviewID int32       `json:"review_id"`
	Rating   pgtype.Int4 `json:"rating"`
	Content  pgtype.Text `json:"content"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReview, arg.ReviewID, arg.Rating, arg.Content)
	var i Review
	err := row.Scan(
		&i.ReviewID,
		&i.UserID,
		&i.MovieID,
		&i.Rating,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
