// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCinema(ctx context.Context, arg CreateCinemaParams) (Cinema, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateShowtime(ctx context.Context, arg CreateShowtimeParams) (Showtime, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCinema(ctx context.Context, cinemaID int32) error
	DeleteMovie(ctx context.Context, movieID int32) error
	DeleteReview(ctx context.Context, reviewID int32) error
	DeleteShowtime(ctx context.Context, showtimeID int32) error
	DeleteTicket(ctx context.Context, ticketID pgtype.UUID) error
	DeleteUser(ctx context.Context, userID int32) error
	GetCinema(ctx context.Context, cinemaID int32) (Cinema, error)
	GetMovie(ctx context.Context, movieID int32) (Movie, error)
	GetPermission(ctx context.Context, permissionID int32) (Permission, error)
	GetReview(ctx context.Context, reviewID int32) (Review, error)
	GetShowtime(ctx context.Context, showtimeID int32) (GetShowtimeRow, error)
	GetTicket(ctx context.Context, ticketID pgtype.UUID) (GetTicketRow, error)
	GetUser(ctx context.Context, userID int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListCinemas(ctx context.Context, arg ListCinemasParams) ([]Cinema, error)
	ListMovies(ctx context.Context, arg ListMoviesParams) ([]Movie, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListReviews(ctx context.Context, arg ListReviewsParams) ([]ListReviewsRow, error)
	ListShowtimes(ctx context.Context, arg ListShowtimesParams) ([]ListShowtimesRow, error)
	ListTickets(ctx context.Context, arg ListTicketsParams) ([]ListTicketsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateCinema(ctx context.Context, arg UpdateCinemaParams) (Cinema, error)
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error)
	UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error)
	UpdateShowtime(ctx context.Context, arg UpdateShowtimeParams) (Showtime, error)
	UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (Ticket, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
