// Code generated by sqlc. DO NOT EDIT.
// This shows the pattern sqlc generates.

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// DBTX interface allows using both pool and transactions
type DBTX interface {
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
}

// Queries is the main interface for database operations
type Queries struct {
	db DBTX
}

// New creates a new Queries instance
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// WithTx returns a new Queries that uses the transaction
func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}

// ============================================================================
// User Queries
// ============================================================================

const getUser = `-- name: GetUser :one
SELECT id, name, email, password_hash, active, created_at, updated_at 
FROM users WHERE id = $1`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var u User
	err := row.Scan(
		&u.ID, &u.Name, &u.Email, &u.PasswordHash,
		&u.Active, &u.CreatedAt, &u.UpdatedAt,
	)
	return u, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, active, created_at, updated_at 
FROM users WHERE email = $1`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var u User
	err := row.Scan(
		&u.ID, &u.Name, &u.Email, &u.PasswordHash,
		&u.Active, &u.CreatedAt, &u.UpdatedAt,
	)
	return u, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, password_hash, active, created_at, updated_at FROM users 
WHERE active = COALESCE($1, active)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3`

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Active, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var users []User
	for rows.Next() {
		var u User
		if err := rows.Scan(
			&u.ID, &u.Name, &u.Email, &u.PasswordHash,
			&u.Active, &u.CreatedAt, &u.UpdatedAt,
		); err != nil {
			return nil, err
		}
		users = append(users, u)
	}
	
	if users == nil {
		users = []User{} // Return empty slice, not nil
	}
	return users, rows.Err()
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, name, email, password_hash, active, created_at, updated_at`

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.PasswordHash)
	var u User
	err := row.Scan(
		&u.ID, &u.Name, &u.Email, &u.PasswordHash,
		&u.Active, &u.CreatedAt, &u.UpdatedAt,
	)
	return u, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET name = COALESCE($2, name),
    email = COALESCE($3, email),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, email, password_hash, active, created_at, updated_at`

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.Email)
	var u User
	err := row.Scan(
		&u.ID, &u.Name, &u.Email, &u.PasswordHash,
		&u.Active, &u.CreatedAt, &u.UpdatedAt,
	)
	return u, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)`

func (q *Queries) UserExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

// ============================================================================
// Post Queries
// ============================================================================

const getPost = `-- name: GetPost :one
SELECT id, user_id, title, content, published, created_at, updated_at 
FROM posts WHERE id = $1`

func (q *Queries) GetPost(ctx context.Context, id int32) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var p Post
	err := row.Scan(
		&p.ID, &p.UserID, &p.Title, &p.Content,
		&p.Published, &p.CreatedAt, &p.UpdatedAt,
	)
	return p, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id, title, content, published)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, content, published, created_at, updated_at`

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost, arg.UserID, arg.Title, arg.Content, arg.Published)
	var p Post
	err := row.Scan(
		&p.ID, &p.UserID, &p.Title, &p.Content,
		&p.Published, &p.CreatedAt, &p.UpdatedAt,
	)
	return p, err
}

const getPostWithAuthor = `-- name: GetPostWithAuthor :one
SELECT 
    p.id, p.title, p.content, p.published, p.created_at,
    u.id as author_id, u.name as author_name, u.email as author_email
FROM posts p
JOIN users u ON p.user_id = u.id
WHERE p.id = $1`

func (q *Queries) GetPostWithAuthor(ctx context.Context, id int32) (GetPostWithAuthorRow, error) {
	row := q.db.QueryRow(ctx, getPostWithAuthor, id)
	var r GetPostWithAuthorRow
	err := row.Scan(
		&r.ID, &r.Title, &r.Content, &r.Published, &r.CreatedAt,
		&r.AuthorID, &r.AuthorName, &r.AuthorEmail,
	)
	return r, err
}

const listPostsWithAuthors = `-- name: ListPostsWithAuthors :many
SELECT 
    p.id, p.title, p.content, p.published, p.created_at,
    u.id as author_id, u.name as author_name
FROM posts p
JOIN users u ON p.user_id = u.id
WHERE p.published = true
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2`

func (q *Queries) ListPostsWithAuthors(ctx context.Context, limit int32, offset int32) ([]ListPostsWithAuthorsRow, error) {
	rows, err := q.db.Query(ctx, listPostsWithAuthors, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var posts []ListPostsWithAuthorsRow
	for rows.Next() {
		var r ListPostsWithAuthorsRow
		if err := rows.Scan(
			&r.ID, &r.Title, &r.Content, &r.Published, &r.CreatedAt,
			&r.AuthorID, &r.AuthorName,
		); err != nil {
			return nil, err
		}
		posts = append(posts, r)
	}

	if posts == nil {
		posts = []ListPostsWithAuthorsRow{}
	}
	return posts, rows.Err()
}
