// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: showtimes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShowtime = `-- name: CreateShowtime :one
INSERT INTO showtimes (movie_id, cinema_id, start_time, price, duration)
VALUES ($1, $2, $3, $4, $5)
RETURNING showtime_id, movie_id, cinema_id, start_time, price, duration
`

type CreateShowtimeParams struct {
	MovieID   int32              `json:"movie_id"`
	CinemaID  int32              `json:"cinema_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	Price     pgtype.Numeric     `json:"price"`
	Duration  int32              `json:"duration"`
}

func (q *Queries) CreateShowtime(ctx context.Context, arg CreateShowtimeParams) (Showtime, error) {
	row := q.db.QueryRow(ctx, createShowtime,
		arg.MovieID,
		arg.CinemaID,
		arg.StartTime,
		arg.Price,
		arg.Duration,
	)
	var i Showtime
	err := row.Scan(
		&i.ShowtimeID,
		&i.MovieID,
		&i.CinemaID,
		&i.StartTime,
		&i.Price,
		&i.Duration,
	)
	return i, err
}

const deleteShowtime = `-- name: DeleteShowtime :exec
DELETE FROM showtimes WHERE showtime_id = $1
`

func (q *Queries) DeleteShowtime(ctx context.Context, showtimeID int32) error {
	_, err := q.db.Exec(ctx, deleteShowtime, showtimeID)
	return err
}

const getShowtime = `-- name: GetShowtime :one
SELECT
    s.showtime_id, s.movie_id, s.cinema_id, s.start_time, s.price, s.duration,
    m.title AS movie_title,
    c.name AS cinema_name
FROM showtimes s
JOIN movies m ON m.movie_id = s.movie_id
JOIN cinemas c ON c.cinema_id = s.cinema_id
WHERE s.showtime_id = $1
`

type GetShowtimeRow struct {
	ShowtimeID int32              `json:"showtime_id"`
	MovieID    int32              `json:"movie_id"`
	CinemaID   int32              `json:"cinema_id"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	Price      pgtype.Numeric     `json:"price"`
	Duration   int32              `json:"duration"`
	MovieTitle string             `json:"movie_title"`
	CinemaName string             `json:"cinema_name"`
}

func (q *Queries) GetShowtime(ctx context.Context, showtimeID int32) (GetShowtimeRow, error) {
	row := q.db.QueryRow(ctx, getShowtime, showtimeID)
	var i GetShowtimeRow
	err := row.Scan(
		&i.ShowtimeID,
		&i.MovieID,
		&i.CinemaID,
		&i.StartTime,
		&i.Price,
		&i.Duration,
		&i.MovieTitle,
		&i.CinemaName,
	)
	return i, err
}

const listShowtimes = `-- name: ListShowtimes :many
SELECT
    s.showtime_id, s.movie_id, s.cinema_id, s.start_time, s.price, s.duration,
    m.title AS movie_title,
    c.name AS cinema_name
FROM showtimes s
JOIN movies m ON m.movie_id = s.movie_id
JOIN cinemas c ON c.cinema_id = s.cinema_id
ORDER BY s.start_time DESC
LIMIT $1 OFFSET $2
`

type ListShowtimesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListShowtimesRow struct {
	ShowtimeID int32              `json:"showtime_id"`
	MovieID    int32              `json:"movie_id"`
	CinemaID   int32              `json:"cinema_id"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	Price      pgtype.Numeric     `json:"price"`
	Duration   int32              `json:"duration"`
	MovieTitle string             `json:"movie_title"`
	CinemaName string             `json:"cinema_name"`
}

func (q *Queries) ListShowtimes(ctx context.Context, arg ListShowtimesParams) ([]ListShowtimesRow, error) {
	rows, err := q.db.Query(ctx, listShowtimes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShowtimesRow{}
	for rows.Next() {
		var i ListShowtimesRow
		if err := rows.Scan(
			&i.ShowtimeID,
			&i.MovieID,
			&i.CinemaID,
			&i.StartTime,
			&i.Price,
			&i.Duration,
			&i.MovieTitle,
			&i.CinemaName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShowtime = `-- name: UpdateShowtime :one
UPDATE showtimes
SET movie_id = $2, cinema_id = $3, start_time = $4, price = $5, duration = $6
WHERE showtime_id = $1
RETURNING showtime_id, movie_id, cinema_id, start_time, price, duration
`

type UpdateShowtimeParams struct {
	ShowtimeID int32              `json:"showtime_id"`
	MovieID    int32              `json:"movie_id"`
	CinemaID   int32              `json:"cinema_id"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	Price      pgtype.Numeric     `json:"price"`
	Duration   int32              `json:"duration"`
}

func (q *Queries) UpdateShowtime(ctx context.Context, arg UpdateShowtimeParams) (Showtime, error) {
	row := q.db.QueryRow(ctx, updateShowtime,
		arg.ShowtimeID,
		arg.MovieID,
		arg.CinemaID,
		arg.StartTime,
		arg.Price,
		arg.Duration,
	)
	var i Showtime
	err := row.Scan(
		&i.ShowtimeID,
		&i.MovieID,
		&i.CinemaID,
		&i.StartTime,
		&i.Price,
		&i.Duration,
	)
	return i, err
}
