// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (showtime_id, user_id, seat_number, payment_status)
VALUES ($1, $2, $3, $4)
RETURNING ticket_id, showtime_id, user_id, seat_number, payment_status
`

type CreateTicketParams struct {
	ShowtimeID    int32       `json:"showtime_id"`
	UserID        int32       `json:"user_id"`
	SeatNumber    string      `json:"seat_number"`
	PaymentStatus pgtype.Text `json:"payment_status"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ShowtimeID,
		arg.UserID,
		arg.SeatNumber,
		arg.PaymentStatus,
	)
	var i Ticket
	err := row.Scan(
		&i.TicketID,
		&i.ShowtimeID,
		&i.UserID,
		&i.SeatNumber,
		&i.PaymentStatus,
	)
	return i, err
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets WHERE ticket_id = $1
`

func (q *Queries) DeleteTicket(ctx context.Context, ticketID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTicket, ticketID)
	return err
}

const getTicket = `-- name: GetTicket :one
SELECT
    t.ticket_id, t.showtime_id, t.user_id, t.seat_number, t.payment_status,
    u.full_name AS user_name,
    u.email AS user_email,
    m.title AS movie_title,
    c.name AS cinema_name,
    s.start_time
FROM tickets t
JOIN users u ON u.user_id = t.user_id
JOIN showtimes s ON s.showtime_id = t.showtime_id
JOIN movies m ON m.movie_id = s.movie_id
JOIN cinemas c ON c.cinema_id = s.cinema_id
WHERE t.ticket_id = $1
`

type GetTicketRow struct {
	TicketID      pgtype.UUID        `json:"ticket_id"`
	ShowtimeID    int32              `json:"showtime_id"`
	UserID        int32              `json:"user_id"`
	SeatNumber    string             `json:"seat_number"`
	PaymentStatus pgtype.Text        `json:"payment_status"`
	UserName      string             `json:"user_name"`
	UserEmail     string             `json:"user_email"`
	MovieTitle    string             `json:"movie_title"`
	CinemaName    string             `json:"cinema_name"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
}

func (q *Queries) GetTicket(ctx context.Context, ticketID pgtype.UUID) (GetTicketRow, error) {
	row := q.db.QueryRow(ctx, getTicket, ticketID)
	var i GetTicketRow
	err := row.Scan(
		&i.TicketID,
		&i.ShowtimeID,
		&i.UserID,
		&i.SeatNumber,
		&i.PaymentStatus,
		&i.UserName,
		&i.UserEmail,
		&i.MovieTitle,
		&i.CinemaName,
		&i.StartTime,
	)
	return i, err
}

const listTickets = `-- name: ListTickets :many
SELECT
    t.ticket_id, t.showtime_id, t.user_id, t.seat_number, t.payment_status,
    u.full_name AS user_name,
    u.email AS user_email,
    m.title AS movie_title,
    c.name AS cinema_name,
    s.start_time
FROM tickets t
JOIN users u ON u.user_id = t.user_id
JOIN showtimes s ON s.showtime_id = t.showtime_id
JOIN movies m ON m.movie_id = s.movie_id
JOIN cinemas c ON c.cinema_id = s.cinema_id
ORDER BY s.start_time DESC
LIMIT $1 OFFSET $2
`

type ListTicketsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListTicketsRow struct {
	TicketID      pgtype.UUID        `json:"ticket_id"`
	ShowtimeID    int32              `json:"showtime_id"`
	UserID        int32              `json:"user_id"`
	SeatNumber    string             `json:"seat_number"`
	PaymentStatus pgtype.Text        `json:"payment_status"`
	UserName      string             `json:"user_name"`
	UserEmail     string             `json:"user_email"`
	MovieTitle    string             `json:"movie_title"`
	CinemaName    string             `json:"cinema_name"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]ListTicketsRow, error) {
	rows, err := q.db.Query(ctx, listTickets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketsRow{}
	for rows.Next() {
		var i ListTicketsRow
		if err := rows.Scan(
			&i.TicketID,
			&i.ShowtimeID,
			&i.UserID,
			&i.SeatNumber,
			&i.PaymentStatus,
			&i.UserName,
			&i.UserEmail,
			&i.MovieTitle,
			&i.CinemaName,
			&i.StartTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketStatus = `-- name: UpdateTicketStatus :one
UPDATE tickets
SET payment_status = $2
WHERE ticket_id = $1
RETURNING ticket_id, showtime_id, user_id, seat_number, payment_status
`

type UpdateTicketStatusParams struct {
	TicketID      pgtype.UUID `json:"ticket_id"`
	PaymentStatus pgtype.Text `json:"payment_status"`
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketStatus, arg.TicketID, arg.PaymentStatus)
	var i Ticket
	err := row.Scan(
		&i.TicketID,
		&i.ShowtimeID,
		&i.UserID,
		&i.SeatNumber,
		&i.PaymentStatus,
	)
	return i, err
}
