// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, phone, full_name, permission_level)
VALUES ($1, $2, $3, $4, $5)
RETURNING user_id, email, password_hash, phone, full_name, is_blocked, permission_level, created_at, updated_at
`

type CreateUserParams struct {
	Email           string      `json:"email"`
	PasswordHash    string      `json:"password_hash"`
	Phone           pgtype.Text `json:"phone"`
	FullName        string      `json:"full_name"`
	PermissionLevel pgtype.Int4 `json:"permission_level"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Phone,
		arg.FullName,
		arg.PermissionLevel,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.FullName,
		&i.IsBlocked,
		&i.PermissionLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT user_id, email, password_hash, phone, full_name, is_blocked, permission_level, created_at, updated_at FROM users WHERE user_id = $1
`

func (q *Queries) GetUser(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.FullName,
		&i.IsBlocked,
		&i.PermissionLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, email, password_hash, phone, full_name, is_blocked, permission_level, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.FullName,
		&i.IsBlocked,
		&i.PermissionLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, email, password_hash, phone, full_name, is_blocked, permission_level, created_at, updated_at FROM users ORDER BY user_id LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.PasswordHash,
			&i.Phone,
			&i.FullName,
			&i.IsBlocked,
			&i.PermissionLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, phone = $3, full_name = $4, is_blocked = $5, permission_level = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
RETURNING user_id, email, password_hash, phone, full_name, is_blocked, permission_level, created_at, updated_at
`

type UpdateUserParams struct {
	UserID          int32       `json:"user_id"`
	Email           string      `json:"email"`
	Phone           pgtype.Text `json:"phone"`
	FullName        string      `json:"full_name"`
	IsBlocked       pgtype.Bool `json:"is_blocked"`
	PermissionLevel pgtype.Int4 `json:"permission_level"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserID,
		arg.Email,
		arg.Phone,
		arg.FullName,
		arg.IsBlocked,
		arg.PermissionLevel,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.FullName,
		&i.IsBlocked,
		&i.PermissionLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
